// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsP2hmkKLRRTuIkkuhCJmYtBGkdLd_Ryo',
    appId: '1:803754240293:web:60a3638e06b51bc6a592cc',
    messagingSenderId: '803754240293',
    projectId: 'av1155-bridgechat',
    authDomain: 'av1155-bridgechat.firebaseapp.com',
    storageBucket: 'av1155-bridgechat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PGxPQBu0MnEyFVb0yeT93_Zfmu511F0',
    appId: '1:803754240293:android:ef449b984c85acaca592cc',
    messagingSenderId: '803754240293',
    projectId: 'av1155-bridgechat',
    storageBucket: 'av1155-bridgechat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxj3d2C4ZlPsIjnoASZosq7uptyieLz7Q',
    appId: '1:803754240293:ios:ffc59e460968a36fa592cc',
    messagingSenderId: '803754240293',
    projectId: 'av1155-bridgechat',
    storageBucket: 'av1155-bridgechat.firebasestorage.app',
    iosBundleId: 'com.example.bridgechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxj3d2C4ZlPsIjnoASZosq7uptyieLz7Q',
    appId: '1:803754240293:ios:ffc59e460968a36fa592cc',
    messagingSenderId: '803754240293',
    projectId: 'av1155-bridgechat',
    storageBucket: 'av1155-bridgechat.firebasestorage.app',
    iosBundleId: 'com.example.bridgechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsP2hmkKLRRTuIkkuhCJmYtBGkdLd_Ryo',
    appId: '1:803754240293:web:a642395fa52fa59ea592cc',
    messagingSenderId: '803754240293',
    projectId: 'av1155-bridgechat',
    authDomain: 'av1155-bridgechat.firebaseapp.com',
    storageBucket: 'av1155-bridgechat.firebasestorage.app',
  );
}
