const Map<String, String> supportedLanguages = {
  // 'Azerbaijani': 'az',
  // 'Basque': 'eu',
  'Bengali': 'bn',
  // 'Bulgarian': 'bg',
  // 'Catalan': 'ca',
  'Chinese': 'zh',
  'Chinese (traditional)': 'zt',
  // 'Czech': 'cs',
  // 'Danish': 'da',
  'Dutch': 'nl',
  'English': 'en',
  // 'Esperanto': 'eo',
  // 'Estonian': 'et',
  // 'Finnish': 'fi',
  'French': 'fr',
  // 'Galician': 'gl',
  'German': 'de',
  // 'Greek': 'el',
  // 'Hebrew': 'he',
  'Hindi': 'hi',
  // 'Hungarian': 'hu',
  'Indonesian': 'id',
  // 'Irish': 'ga',
  'Italian': 'it',
  'Japanese': 'ja',
  'Korean': 'ko',
  // 'Latvian': 'lv',
  // 'Lithuanian': 'lt',
  'Malay': 'ms',
  // 'Norwegian': 'nb',
  // 'Persian': 'fa',
  'Polish': 'pl',
  'Portuguese': 'pt',
  // 'Portuguese (Brazil)': 'pb',
  // 'Romanian': 'ro',
  'Russian': 'ru',
  // 'Slovak': 'sk',
  // 'Slovenian': 'sl',
  'Spanish': 'es',
  // 'Swedish': 'sv',
  // 'Tagalog': 'tl',
  // 'Thai': 'th',
  'Turkish': 'tr',
  // 'Ukrainian': 'uk',
  // 'Urdu': 'ur',
};
